#!/bin/bash
# Setup Team Configuration
# Run this once per team to configure their workspace
#
# Usage: ./scripts/setup-team.sh <team_number> <team_name> [body_color] [turret_color] [radar_color] [bullet_color]
# Example: ./scripts/setup-team.sh 1 "ThunderBots" "BLUE" "BLUE" "ORANGE" "YELLOW"

TEAM_NUM=$1
TEAM_NAME=$2
BODY_COLOR=${3:-BLUE}
TURRET_COLOR=${4:-$BODY_COLOR}
RADAR_COLOR=${5:-ORANGE}
BULLET_COLOR=${6:-YELLOW}

echo "🎯 Tank Royale Hackathon - Team Setup"
echo ""

# Validate team number
if [ -z "$TEAM_NUM" ]; then
    echo "❌ Error: Team number is required"
    echo ""
    echo "Usage: ./scripts/setup-team.sh <team_number> <team_name> [body_color] [turret_color] [radar_color] [bullet_color]"
    echo ""
    echo "Examples:"
    echo "  ./scripts/setup-team.sh 1 \"ThunderBots\""
    echo "  ./scripts/setup-team.sh 2 \"FireStorm\" \"RED\" \"RED\" \"ORANGE\" \"YELLOW\""
    echo "  ./scripts/setup-team.sh 3 \"CodeNinjas\" \"#00FF00\" \"#00AA00\" \"#FFFF00\" \"#FF00FF\""
    echo ""
    echo "Available color names: RED, BLUE, GREEN, YELLOW, ORANGE, PURPLE, CYAN, MAGENTA, WHITE, BLACK"
    echo "Or use hex format: #RRGGBB"
    exit 1
fi

if [[ ! "$TEAM_NUM" =~ ^[1-4]$ ]]; then
    echo "❌ Invalid team number: $TEAM_NUM"
    echo "   Team number must be 1, 2, 3, or 4"
    exit 1
fi

# Validate team name
if [ -z "$TEAM_NAME" ]; then
    echo "❌ Error: Team name is required"
    echo ""
    echo "Usage: ./scripts/setup-team.sh <team_number> <team_name> [body_color] [turret_color] [radar_color] [bullet_color]"
    exit 1
fi

# Set workspace
TEAM_WORKSPACE="tank-royale/teams/team$TEAM_NUM"

# Create team config file
cd "$(dirname "$0")/.."
cat > .team-config << EOF
# Team Configuration
# Auto-generated by setup-team.sh

TEAM_NUMBER=$TEAM_NUM
TEAM_NAME=$TEAM_NAME
TEAM_WORKSPACE=$TEAM_WORKSPACE

# Bot Colors
BODY_COLOR=$BODY_COLOR
TURRET_COLOR=$TURRET_COLOR
RADAR_COLOR=$RADAR_COLOR
BULLET_COLOR=$BULLET_COLOR
EOF

echo ""
echo "✅ Team configuration saved!"
echo ""
echo "📋 Your Team Info:"
echo "   Team Number: $TEAM_NUM"
echo "   Team Name: $TEAM_NAME"
echo "   Workspace: $TEAM_WORKSPACE"
echo ""
echo "🎨 Bot Colors:"
echo "   Body: $BODY_COLOR"
echo "   Turret: $TURRET_COLOR"
echo "   Radar: $RADAR_COLOR"
echo "   Bullets: $BULLET_COLOR"
echo ""

# Append team context to AI assistant files
echo "🤖 Configuring AI assistants for your team..."

# Update CLAUDE.md
if ! grep -q "## YOUR TEAM CONFIGURATION" CLAUDE.md; then
    cat >> CLAUDE.md << 'TEAMEOF'

---

## YOUR TEAM CONFIGURATION

**This section is auto-generated by setup-team.sh**

TEAMEOF
fi

# Replace team config section
sed -i.bak '/## YOUR TEAM CONFIGURATION/,$d' CLAUDE.md
cat >> CLAUDE.md << TEAMEOF

---

## YOUR TEAM CONFIGURATION

**This section is auto-generated by setup-team.sh**

You are assisting **Team $TEAM_NUM: $TEAM_NAME**

**Team Workspace:** \`$TEAM_WORKSPACE/\`

### Team Bot Colors

When creating or modifying bots, use these team colors:

- **Body Color:** \`$BODY_COLOR\`
- **Turret Color:** \`$TURRET_COLOR\`
- **Radar Color:** \`$RADAR_COLOR\`
- **Bullet Color:** \`$BULLET_COLOR\`

**Note:** The \`./scripts/create-bot.sh\` script will automatically apply these colors to new bots. If the team wants to change colors later, they can re-run \`./scripts/setup-team.sh\` or ask you to help modify the colors in existing bot code.

### Important Reminders for AI Assistant:

1. **Always work in the team workspace:** \`$TEAM_WORKSPACE/\`
2. **When creating bots:** Use \`./scripts/create-bot.sh <BotName>\` (will auto-place in your team folder with team colors)
3. **When referencing bot files:** Use paths relative to \`$TEAM_WORKSPACE/\`
4. **Team bot location:** \`$TEAM_WORKSPACE/<YourBotName>/\`
5. **Color configuration:** If the team wants different colors, help them run \`./scripts/setup-team.sh\` again, or update the bot's \`run()\` method to call the \`setBodyColor()\`, \`setTurretColor()\`, \`setRadarColor()\`, and \`setBulletColor()\` methods.

### Quick Commands for This Team:

\`\`\`bash
# Navigate to team workspace
cd $TEAM_WORKSPACE

# Create a new bot (from repo root)
./scripts/create-bot.sh $TEAM_NAME-Bot

# Test your bot
cd $TEAM_WORKSPACE/<YourBotName>
./<YourBotName>.sh

# Launch GUI to test battles
./scripts/start-gui.sh
\`\`\`

**Remember:** You are Team $TEAM_NUM ($TEAM_NAME) - always work in \`$TEAM_WORKSPACE/\` and use the team's configured colors!
TEAMEOF

# Update copilot-instructions.md
if ! grep -q "## YOUR TEAM CONFIGURATION" .github/copilot-instructions.md; then
    cat >> .github/copilot-instructions.md << 'TEAMEOF'

---

## YOUR TEAM CONFIGURATION

**This section is auto-generated by setup-team.sh**

TEAMEOF
fi

# Replace team config section
sed -i.bak '/## YOUR TEAM CONFIGURATION/,$d' .github/copilot-instructions.md
cat >> .github/copilot-instructions.md << TEAMEOF

---

## YOUR TEAM CONFIGURATION

**This section is auto-generated by setup-team.sh**

You are assisting **Team $TEAM_NUM: $TEAM_NAME**

**Team Workspace:** \`$TEAM_WORKSPACE/\`

### Team Bot Colors

When creating or modifying bots, use these team colors:

- **Body Color:** \`$BODY_COLOR\`
- **Turret Color:** \`$TURRET_COLOR\`
- **Radar Color:** \`$RADAR_COLOR\`
- **Bullet Color:** \`$BULLET_COLOR\`

**Note:** The \`./scripts/create-bot.sh\` script will automatically apply these colors to new bots. If the team wants to change colors later, they can re-run \`./scripts/setup-team.sh\` or ask you to help modify the colors in existing bot code.

### Important Reminders for AI Assistant:

1. **Always work in the team workspace:** \`$TEAM_WORKSPACE/\`
2. **When creating bots:** Use \`./scripts/create-bot.sh <BotName>\` (will auto-place in your team folder with team colors)
3. **When referencing bot files:** Use paths relative to \`$TEAM_WORKSPACE/\`
4. **Team bot location:** \`$TEAM_WORKSPACE/<YourBotName>/\`
5. **Color configuration:** If the team wants different colors, help them run \`./scripts/setup-team.sh\` again, or update the bot's \`run()\` method to call the \`setBodyColor()\`, \`setTurretColor()\`, \`setRadarColor()\`, and \`setBulletColor()\` methods.

### Quick Commands for This Team:

\`\`\`bash
# Navigate to team workspace
cd $TEAM_WORKSPACE

# Create a new bot (from repo root)
./scripts/create-bot.sh $TEAM_NAME-Bot

# Test your bot
cd $TEAM_WORKSPACE/<YourBotName>
./<YourBotName>.sh

# Launch GUI to test battles
./scripts/start-gui.sh
\`\`\`

**Remember:** You are Team $TEAM_NUM ($TEAM_NAME) - always work in \`$TEAM_WORKSPACE/\` and use the team's configured colors!
TEAMEOF

# Clean up backup files
rm -f CLAUDE.md.bak .github/copilot-instructions.md.bak

echo "✅ AI assistants configured for Team $TEAM_NUM!"
echo ""
echo "🚀 Next steps:"
echo "   1. Run: ./scripts/verify-setup.sh"
echo "   2. Run: ./scripts/create-bot.sh ${TEAM_NAME}Bot"
echo "   3. Start coding in: $TEAM_WORKSPACE/"
echo ""
echo "Your AI assistant (Claude Code/GitHub Copilot) now knows:"
echo "   - Your team number and name"
echo "   - Your team workspace"
echo "   - Where to create and find your bot files"
echo ""
echo "Good luck, Team $TEAM_NAME! 🏆"
