#!/bin/bash
# Start Tank Royale GUI

cd "$(dirname "$0")/.."

# Auto-configure bot directories if not already done
if [ ! -f "gui.properties" ]; then
    echo "🔧 First-time setup: Configuring bot directories..."

    # Get absolute path to repository root
    REPO_ROOT="$(pwd)"

    # Create gui.properties with absolute paths
    cat > gui.properties << EOF
# Tank Royale GUI Configuration
# Auto-generated by start-gui.sh

# Bot directories (comma-separated: path,enabled,path,enabled,...)
bot-directories=$REPO_ROOT/tank-royale/sample-bots,true,$REPO_ROOT/tank-royale/teams/team1,true,$REPO_ROOT/tank-royale/teams/team2,true,$REPO_ROOT/tank-royale/teams/team3,true,$REPO_ROOT/tank-royale/teams/team4,true

# TPS (Turns Per Second)
tps=30
EOF

    echo "✅ Bot directories configured!"
    echo ""
fi

echo "🚀 Launching Tank Royale GUI..."
java -jar tank-royale/robocode-tankroyale-gui-0.33.1.jar
