#!/bin/bash
# Verify Tank Royale Setup

echo "🔍 Verifying Tank Royale Setup..."
echo ""

# Check team configuration first
if [ -f ".team-config" ]; then
    source .team-config
    if [ -n "$TEAM_NUMBER" ] && [ -n "$TEAM_NAME" ]; then
        echo "✅ Team configured: Team $TEAM_NUMBER ($TEAM_NAME)"
    else
        echo "⚠️  Team configuration incomplete"
        echo ""
        echo "💡 Ask your AI assistant to help you set up your team!"
        echo "   Example: 'Help me set up our team. We are team 2 and want to be called FireStorm'"
        echo ""
        exit 1
    fi
else
    echo "⚠️  Team not configured yet"
    echo ""
    echo "💡 Ask your AI assistant to help you set up your team!"
    echo "   Example prompts:"
    echo "   - 'Help me set up our team for the hackathon'"
    echo "   - 'We are team 1, let's call ourselves ThunderBots with blue colors'"
    echo "   - 'Configure our team as team 3, brainstorm a cool name for us'"
    echo ""
    exit 1
fi

echo ""

# Check Java
if command -v java &> /dev/null; then
    JAVA_VERSION=$(java -version 2>&1 | head -n 1)
    echo "✅ Java installed: $JAVA_VERSION"
else
    echo "❌ Java not found"
    echo "   Please install Java 11+ (see SETUP.md)"
    exit 1
fi

# Check Tank Royale GUI
if [ -f "tank-royale/robocode-tankroyale-gui-0.33.1.jar" ]; then
    echo "✅ Tank Royale GUI found"
else
    echo "❌ Tank Royale GUI not found"
    exit 1
fi

# Check Bot API
if [ -f "tank-royale/lib/robocode-tankroyale-bot-api-0.33.1.jar" ]; then
    echo "✅ Bot API found"
else
    echo "❌ Bot API not found"
    exit 1
fi

# Check sample bots
if [ -d "tank-royale/sample-bots/MyFirstBot" ]; then
    echo "✅ Sample bots found"
else
    echo "❌ Sample bots not found"
    exit 1
fi

# Configure bot directories
echo ""
echo "🔧 Configuring bot directories..."

# Get absolute path to repository root
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Create/update gui.properties from template
sed "s|{{REPO_ROOT}}|$REPO_ROOT|g" "$SCRIPT_DIR/templates/gui.properties.template" > "$REPO_ROOT/gui.properties"

echo "✅ Bot directories configured"

# Create/update game-setups.properties from template
# Configure number of rounds (default: 3 for faster testing)
NUMBER_OF_ROUNDS=3

sed "s|{{NUMBER_OF_ROUNDS}}|$NUMBER_OF_ROUNDS|g" "$SCRIPT_DIR/templates/game-setups.properties.template" > "$REPO_ROOT/tank-royale/game-setups.properties"

echo "✅ Game setup defaults configured ($NUMBER_OF_ROUNDS rounds for faster testing)"

# Note: server.properties is auto-generated by the GUI

echo ""
echo "🎉 Setup verification complete! You're ready for the hackathon!"
echo ""
echo "📋 Your Team: $TEAM_NAME (Team $TEAM_NUMBER)"
echo "📁 Workspace: $TEAM_WORKSPACE"
echo ""
echo "Next steps:"
echo "  1. Launch GUI:        ./scripts/start-gui.sh"
echo "  2. Create your bot:   ./scripts/create-bot.sh ${TEAM_NAME}Bot"
echo "  3. Start coding in:   $TEAM_WORKSPACE/"
